services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    volumes:
      - ./app.py:/app/app.py
      - ./simglucose:/app/simglucose
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - OPENAPS_URL=http://openaps:3000
    depends_on:
      - openaps
    restart: unless-stopped

  openaps:
    build:
      context: ../igs_oref0
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../igs_oref0/server.js:/app/server.js
      - ../igs_oref0/lib:/app/lib
    restart: unless-stopped